version: '3.6'

services:
  gateway:
    image: quay.io/datawire/ambassador:0.40.0
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - proxy
      - peatio
      - barong
      - ranger
    volumes:
      - ../config/gateway:/ambassador/ambassador-config:ro
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: www.wb.local'
      traefik.port: 80
